# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginregistration_app', '0002_delete_usermanangement'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bday',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, to='loginregistration_app.User'),
        ),
    ]
