# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginregistration_app', '0003_auto_20170927_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='_user_friends_+', to='loginregistration_app.User'),
        ),
    ]
